### ISSUE TITLE
Stun server doesn't gather candidates

### ISSUE THREAD

**Issue by saroamirkhanyan** [paullouisageneau/violet#2] opened 2021-05-25 13:28 UTC
Hey, turn server works perfectly, but stun server doesn't work properly it doesn't gather candidates.

**Comment by paullouisageneau** [comment] 2021-05-25 17:18
Could you please provide more information about your setup? What is the client? What URL do  you use for the STUN server? How is the server hosted (IPv4 or IPv6)?

**Comment by NorayrMamulyan** [comment] 2021-05-25 20:29
I have downloaded the project and built it how in docs, then i run it.
I checked the server using https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ site.
Turn server worked but stun didn't.

**Comment by saroamirkhanyan** [comment] 2021-05-25 20:40
> Could you please provide more information about your setup? What is the client? What URL do you use for the STUN server? How is the server hosted (IPv4 or IPv6)?



> I have downloaded the project and built it how in docs, then i run it.
> I checked the server using https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ site.
> Turn server worked but stun didn't.

The same problem.

**Comment by saroamirkhanyan** [comment] 2021-05-25 20:43
> Could you please provide more information about your setup? What is the client? What URL do you use for the STUN server? How is the server hosted (IPv4 or IPv6)?

I have nothing changed, I did what in docs is written.

**Comment by paullouisageneau** [comment] 2021-05-25 21:03
The STUN server URL you set in the client is independent from how to build and run the project. On my side, the server works with the trickle-ice page for both Firefox and Chromium, so I need to know some details in order to reproduce the issue. What URL do you use for the STUN server?

A possible issue is that you set a hostname resolving to both IPv6 and IPv4 for the STUN server. This configuration will lead the browser to make the STUN request for IPv6, which most of the time won't give a new candidate address as IPv6 normally has no NAT. Therefore, the STUN server URL must instead use IPv4 in most circumstances.

**Comment by saroamirkhanyan** [comment] 2021-05-26 11:00
For STUN server I have used stun:(local_network's_ip_addr):3478

**Comment by saroamirkhanyan** [comment] 2021-05-26 11:35
After checking the stun server in global network it has worked.
Thank you.

**Comment by paullouisageneau** [comment] 2021-05-26 12:12
> For STUN server I have used stun:(local_network's_ip_addr):3478
>
> After checking the stun server in global network it has worked.

Indeed, a STUN server on the local network will only reflect the local address. Since it won't be different from the corresponding host candidate, the client won't emit a server reflexive candidate.

**Closed as completed by paullouisageneau** 2021-05-26 12:12 UTC
